# Generated by Django 6.0 on 2025-12-26 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=100)),
                ('cnic', models.CharField(blank=True, max_length=20)),
                ('contact_info', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='active', max_length=20)),
            ],
        ),
    ]
