# Generated by Django 6.0 on 2025-12-27 13:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_vendorbill_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('current_quantity', models.IntegerField(default=0)),
                ('threshold', models.IntegerField(default=10)),
                ('unit', models.CharField(default='kg', max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='client',
            old_name='company_name',
            new_name='company',
        ),
        migrations.RemoveField(
            model_name='client',
            name='cnic',
        ),
        migrations.RemoveField(
            model_name='client',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='client',
            name='status',
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
