# Generated by Django 6.0 on 2025-12-28 17:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_material_current_quantity_material_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
