# Generated by Django 6.0 on 2025-12-28 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_material_created_at'),
    ]

    operations = [
    ]
