# Generated by Django 6.0 on 2025-12-28 20:00

from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ('core', '0011_merge_20251229_0041'),  # ✅ Correct parent
    ]