# Generated by Django merge command
from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ('core', '0011_merge_20251229_0041'),
        ('core', '0012_auto_20251229_0100'),
    ]

    operations = []