# Generated by Django 6.0 on 2025-12-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20251229_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('upi', 'UPI'), ('other', 'Other')], default='bank_transfer', max_length=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='max_quantity',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='material',
            name='threshold',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
    ]
