# Generated by Django 6.0 on 2025-12-29 14:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_order_paid_amount_order_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('upi', 'UPI'), ('other', 'Other')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client_name', models.CharField(max_length=100)),
                ('client_id', models.IntegerField()),
                ('order_id_display', models.CharField(max_length=50)),
                ('order_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company_name', models.CharField(default='Penta Industries', max_length=100)),
                ('company_address', models.TextField(default='123 Chemical Park, Mumbai, India')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
